- name: Configure Oh My Zsh with plugins
  hosts: all
  become: true
  tasks:
    # Ensure git is installed
    - name: Install git
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    -  name: Create .zshrc file
       file:
        path: "/home/drego/.zshrc"
        state: touch
        mode: '0644'
        become: yes
        become_user: drego


    # Ensure zsh is installed
    - name: Install zsh and terminator
      package:
        name: zsh, terminator, wget, curl
        state: present

    - name: Change default shell to zsh
      user:
        name: "{{ ansible_user }}"
        shell: /bin/zsh

    # Clone oh-my-zsh repository if not already installed
    - name: Clone Oh My Zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: ~/.oh-my-zsh
        force: false
        clone: yes
      become: false
      when: not ansible_os_family.startswith('Windows')
    #Clone powerlevel10k
    - name: Clone powerlevel10k theme
      git:
        repo: https://github.com/romkatv/powerlevel10k.git
        dest: "/home/drego/.oh-my-zsh/custom/themes/powerlevel10k"
        depth: 1
        update: yes
        force: false
    
    - name: Ensure font directory exists
      file:
        path: "/home/drego/.local/share/fonts"
        state: directory
        mode: '0755'

    - name: Download the font file
      get_url:
        url: "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
        dest: "/home/drego/.local/share/fonts/MesloLGS NF Regular.ttf"
        mode: '0644'

    - name: Refresh the font cache
      command: fc-cache -fv
      args:
        warn: false

    - name: Verify font installation
      shell: |
        fc-list | grep -i "MesloLGS NF Regular"
      register: font_check
      failed_when: "'MesloLGS NF Regular' not in font_check.stdout"

    - name: Notify user
      debug:
        msg: "MesloLGS NF Regular font installed successfully!"

    - name: Copy Terminator config file
      copy:
        src: "/home/drego/playbooks/files/terminator.cfg"
        dest: "/home/drego/.config/terminator/config"
        mode: '0644'


    # Install zsh-autosuggestions plugin
    - name: Install zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      become: false

    # Install zsh-syntax-highlighting plugin
    - name: Install zsh-syntax-highlighting
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
      become: false

    # Push local custom zshrc to remote machine

    - name: Push out zshrc configuration
      copy:
        src: /home/drego/playbooks/files/.zshrc
        dest: ~/.zshrc
        mode: '0644'
      become: no
      become_user: drego

    # Update .zshrc to include plugins
    - name: Ensure plugins are added to .zshrc
      lineinfile:
        path: ~/.zshrc
        regexp: '^plugins='
        line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting)'
        state: present
      become: false

    # Source the zshrc file to activate changes
    - name: Reload zsh configuration
      shell: source ~/.zshrc
      args:
        executable: /bin/zsh
      # become: no
      # become_user: drego
    
